[package]
name = "liquity-base"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anchor-lang = "0.13.0"
borsh = "0.9.0"
borsh-derive = "0.9.0"
solana-program = "1.7.8"
